use bookstore;
INSERT INTO books (book_isbn, book_title, book_author, book_image, book_descr, book_price, publisherid, book_qty) VALUES
('978-0-321-94786-4', 'Now you can learn how to design mobile apps for both Apples iOS and Googles Android platforms with just one book. Learning Mobile App Development is the only lesson that covers both iOS and Android in simultaneously, making it ideal for students and professionals. You can master any platform, or both, with this guide, and obtain a better grasp of the challenges that arise when designing mobile apps.Youll learn the complete mobile app development lifecycle, from planning to licencing and distribution, by creating an actual functional app on both iOS and Android. Each tutorial in this book has been thoroughly tested in real developer training courses and has been carefully developed to support readers with a wide range of backgrounds. Youll also discover a quick, practical introduction to Objective-C, Apples native language, if youre new to iOS.', '30.00', 6, 100),
('978-0-7303-1484-4', 'Doing Good by Doing Good teaches businesses how to boost profits by creating an engaging, authentic, and business-enhancing programme that benefits both employees and the company. Peter Baines, an international CSR consultant, describes the Australian CSR landscape and the variables that make up a programme that benefits everyone involved by drawing on lessons learned through his difficulties as a police officer, forensic investigator, and creator of Hands Across the Water. Case studies demonstrate the true impact of CSR on company and society, with clear instructions on how to maximise participation, engage all employees, and improve the bottom line.Companies that are focusing on producing shared value in meeting societal concerns while also generating substantial economic returns are highlighted in the case studies.Consumers today expect large corporations with ever-increasing earnings to contribute back to the communities from which they derive their riches. At the same time, stockholders are clamouring for a piece of the action and cheering the increase in dividends. Doing Good via Doing Good assists businesses in developing a strategy for achieving this goal.', '25.00', 2, 150),
('978-1-118-94924-5', 'Programmable Logic Controllers (PLCs), which are widely used in industrial and manufacturing automation, perform a wide range of electromechanical tasks with multiple input and output arrangements, and are specifically designed to operate in harsh environments such as automotive and chemical plants. Programmable Logic Controllers: A Practical Approach Using CoDeSys is a hands-on guide that will help you quickly gain proficiency in the development and operation of PLCs based on the IEC 61131-3 standard. The author takes a highly practical approach to PLC design by using real-world examples and the freely available* software tool CoDeSys, which is widely used in industrial design automation projects.CoDeSys, the design tool, also includes a built-in simulator / soft PLC, allowing the reader to perform exercises and test the examples.', '40.00', 2, 75),
('978-1-1180-2669-4', 'To realise JavaScripts full potential, you must first understand its nature, history, and limitations. To that end, this revised edition of the best-selling book by veteran author and JavaScript guru Nicholas C. Zakas covers JavaScript from its inception to its current incarnations, which include the DOM, Ajax, and HTML5. Zakas demonstrates how to extend this powerful language to meet specific requirements and create dynamic web user interfaces that blur the line between desktop and internet. By the end of the book, youll have a solid understanding of the significant advances in web development as they relate to JavaScript, which youll be able to apply to your next website.', '20.00', 1, 95),
('978-1-44937-019-0', 'Learning Web App Development', 'Semmy Purewal', 'web_app_dev.jpg', 'Grasp the fundamentals of web application development by building a simple database-backed app from scratch, using HTML, JavaScript, and other open source tools. Through hands-on tutorials, this practical guide shows inexperienced web app developers how to create a user interface, write a server, build client-server communication, and use a cloud-based service to deploy the application.\r\n\r\nEach chapter includes practice problems, full examples, and mental models of the development workflow. Ideal for a college-level course, this book helps you get started with web app development by providing you with a solid grounding in the process.', '35.00', 3, 100),
('978-1-44937-075-6', 'Beautiful JavaScript', 'Anton Kovalyov', 'beauty_js.jpg', 'JavaScript is arguably the most polarizing and misunderstood programming language in the world. Many have attempted to replace it as the language of the Web, but JavaScript has survived, evolved, and thrived. Why did a language created in such hurry succeed where others failed?\r\n\r\nThis guide gives you a rare glimpse into JavaScript from people intimately familiar with it. Chapters contributed by domain experts such as Jacob Thornton, Ariya Hidayat, and Sara Chipps show what they love about their favorite language - whether it''s turning the most feared features into useful tools, or how JavaScript can be used for self-expression.', '45.00', 3, 120),
('978-1-4571-0402-2', 'Professional ASP.NET 4 in C# and VB', 'Scott Hanselman', 'pro_asp4.jpg', 'ASP.NET is about making you as productive as possible when building fast and secure web applications. Each release of ASP.NET gets better and removes a lot of the tedious code that you previously needed to put in place, making common ASP.NET tasks easier. With this book, an unparalleled team of authors walks you through the full breadth of ASP.NET and the new and exciting capabilities of ASP.NET 4. The authors also show you how to maximize the abundance of features that ASP.NET offers to make your development process smoother and more efficient.', '25.00', 1, 60),
('978-1-484216-40-8', 'Android Studio New Media Fundamentals', 'Wallace Jackson', 'android_studio.jpg', 'Android Studio New Media Fundamentals is a new media primer covering concepts central to multimedia production for Android including digital imagery, digital audio, digital video, digital illustration and 3D, using open source software packages such as GIMP, Audacity, Blender, and Inkscape. These professional software packages are used for this book because they are free for commercial use. The book builds on the foundational concepts of raster, vector, and waveform (audio), and gets more advanced as chapters progress, covering what new media assets are best for use with Android Studio as well as key factors regarding the data footprint optimization work process and why new media content and new media data optimization is so important.', '50.00', 4, 100),
('978-1-484217-26-9', 'C++ 17 Quick Syntax Reference, 2nd Edition', '	Mikael Olsson', 'c_17_quick.jpg', 'This updated handy quick C++ 14 guide is a condensed code and syntax reference based on the newly updated C++ 14 release of the popular programming language. It presents the essential C++ syntax in a well-organized format that can be used as a handy reference.\r\n\r\nYou won''t find any technical jargon, bloated samples, drawn out history lessons, or witty stories in this book. What you will find is a language reference that is concise, to the point and highly accessible. The book is packed with useful information and is a must-have for any C++ programmer.\r\n\r\nIn the C++ 14 Quick Syntax Reference, Second Edition, you will find a concise reference to the C++ 14 language syntax. It has short, simple, and focused code examples. This book includes a well laid out table of contents and a comprehensive index allowing for easy review.', '20.00', 4, 300),
('978-1-49192-706-9', 'C# 5.0 in a Nutshell, 5th Edition', 'Joseph Albahari, Ben Albahari', 'c_sharp_5.jpg', 'When you have questions about C# 6.0 or the .NET CLR and its core Framework assemblies, this bestselling guide has the answers you need. C# has become a language of unusual flexibility and breadth since its premiere in 2000, but this continual growth means there''s still much more to learn.\r\n\r\nOrganized around concepts and use cases, this thoroughly updated sixth edition provides intermediate and advanced programmers with a concise map of C# and .NET knowledge. Dive in and discover why this Nutshell guide is considered the definitive reference on C#.', '60.00', 3, 250);

select * from books;

INSERT INTO customers (customerid, fname, lname, address, city, postal_code, country) VALUES
(null, 'milen', 'thomas', '228 albert street', 'waterloo', 'n2e2x7', 'Canada');

INSERT INTO publisher (publisherid, publisher_name) VALUES
(null, 'Wrox'),
(null, 'Wiley'),
(null, 'O''Reilly Media'),
(null, 'Apress'),
(null, 'Packt Publishing'),
(null, 'Addison-Wesley');

