use bookstore;
INSERT INTO books (book_isbn, book_title, book_author, book_image, book_descr, book_price, publisherid, book_qty) VALUES
('978-0-321-94786-4', 'Now you can learn how to design mobile apps for both Apples iOS and Googles Android platforms with just one book. Learning Mobile App Development is the only lesson that covers both iOS and Android in simultaneously, making it ideal for students and professionals. You can master any platform, or both, with this guide, and obtain a better grasp of the challenges that arise when designing mobile apps.Youll learn the complete mobile app development lifecycle, from planning to licencing and distribution, by creating an actual functional app on both iOS and Android. Each tutorial in this book has been thoroughly tested in real developer training courses and has been carefully developed to support readers with a wide range of backgrounds. Youll also discover a quick, practical introduction to Objective-C, Apples native language, if youre new to iOS.', '30.00', 6, 100),
('978-0-7303-1484-4', 'Doing Good by Doing Good teaches businesses how to boost profits by creating an engaging, authentic, and business-enhancing programme that benefits both employees and the company. Peter Baines, an international CSR consultant, describes the Australian CSR landscape and the variables that make up a programme that benefits everyone involved by drawing on lessons learned through his difficulties as a police officer, forensic investigator, and creator of Hands Across the Water. Case studies demonstrate the true impact of CSR on company and society, with clear instructions on how to maximise participation, engage all employees, and improve the bottom line.Companies that are focusing on producing shared value in meeting societal concerns while also generating substantial economic returns are highlighted in the case studies.Consumers today expect large corporations with ever-increasing earnings to contribute back to the communities from which they derive their riches. At the same time, stockholders are clamouring for a piece of the action and cheering the increase in dividends. Doing Good via Doing Good assists businesses in developing a strategy for achieving this goal.', '25.00', 2, 150),
('978-1-118-94924-5', 'Programmable Logic Controllers (PLCs), which are widely used in industrial and manufacturing automation, perform a wide range of electromechanical tasks with multiple input and output arrangements, and are specifically designed to operate in harsh environments such as automotive and chemical plants. Programmable Logic Controllers: A Practical Approach Using CoDeSys is a hands-on guide that will help you quickly gain proficiency in the development and operation of PLCs based on the IEC 61131-3 standard. The author takes a highly practical approach to PLC design by using real-world examples and the freely available* software tool CoDeSys, which is widely used in industrial design automation projects.CoDeSys, the design tool, also includes a built-in simulator / soft PLC, allowing the reader to perform exercises and test the examples.', '40.00', 2, 75),
('978-1-1180-2669-4', 'To realise JavaScripts full potential, you must first understand its nature, history, and limitations. To that end, this revised edition of the best-selling book by veteran author and JavaScript guru Nicholas C. Zakas covers JavaScript from its inception to its current incarnations, which include the DOM, Ajax, and HTML5. Zakas demonstrates how to extend this powerful language to meet specific requirements and create dynamic web user interfaces that blur the line between desktop and internet. By the end of the book, youll have a solid understanding of the significant advances in web development as they relate to JavaScript, which youll be able to apply to your next website.', '20.00', 1, 95),
('978-1-44937-019-0', 'Learn the fundamentals of web application development by creating a simple database-backed app from the ground up with HTML, JavaScript, and other open source tools. This practical guide teaches inexperienced web app developers how to create a user interface, write a server, implement client-server communication, and deploy the application using a cloud-based service through hands-on tutorials. Each chapter contains practise problems, detailed examples, and mental models of the development workflow. This book, which is appropriate for a college-level course, assists you in getting started with web app development by providing a solid foundation in the process.', '35.00', 3, 100),
('978-1-44937-075-6', 'JavaScript is widely regarded as the worlds most divisive and misunderstood programming language. Many have tried to replace JavaScript as the Webs primary language, but it has survived, evolved, and thrived. Why did a language born in such haste succeed where others failed? This guide provides a rare look at JavaScript from people who know it well. Domain experts such as Jacob Thornton, Ariya Hidayat, and Sara Chipps contribute chapters that demonstrate what they love about their favourite language, whether its turning the most feared features into useful tools or using JavaScript for self-expression.', '45.00', 3, 120),
('978-1-4571-0402-2', 'When it comes to building fast and secure web applications, ASP.NET is all about making you as productive as possible. Each ASP.NET release improves and removes a lot of the tedious code that was previously required, making common ASP.NET tasks easier. With this book, an unrivalled team of authors takes you through the entire scope of ASP.NET as well as the new and exciting capabilities of ASP.NET 4. The authors also show you how to make the most of the many features that ASP.NET has to offer in order to make your development process run more smoothly and efficiently.', '25.00', 1, 60),
('978-1-484216-40-8', 'Android Studio New Media Fundamentals is a new media primer that covers concepts central to multimedia production for Android, such as digital imagery, digital audio, digital video, digital illustration, and 3D, using open source software packages such as GIMP, Audacity, Blender, and Inkscape. Because they are free for commercial use, these professional software packages were used for this book.The book builds on the fundamental concepts of raster, vector, and waveform (audio) and progresses through the chapters, covering what new media assets are best for use with Android Studio as well as key factors regarding the data footprint optimization work process and why new media content and new media data optimization is so important.', '50.00', 4, 100),
('978-1-484217-26-9', 'This handy fast C++ 17 tutorial is a condensed code and grammar reference based on the popular programming languages freshly updated C++ 14 edition. It covers the core C++ syntax in an easy-to-understand manner that may be used as a reference. This book is devoid of technical jargon, bloated samples, lengthy history lessons, or amusing stories. Youll find a succinct, to-the-point, and very accessible language reference. The book contains a wealth of important material and is a must-have for every C++ coder.Youll discover a brief guide to the C++ 14 language syntax in the C++ 14 Quick Syntax Reference, Second Edition. It includes code examples that are short, basic, and focused. This book has a well-organized table of contents and a complete index for convenient reference.', '20.00', 4, 300),
('978-1-49192-706-9', 'This best-selling book answers all of your questions about C# 5.0, the.NET CLR, and the Frameworks key components. C# has evolved into a language with outstanding flexibility and depth since its release in 2000, but theres still a lot to learn. This completely revised sixth edition, organised around concepts and use cases, offers intermediate and advanced programmers a concise map of C# and.NET knowledge. By diving in, youll see why this Nutshell guide is recognised as the ultimate C# reference.This best-selling book answers all of your questions about C# 6.0, the.NET CLR, and the Frameworks key components. C# has evolved into a language with outstanding flexibility and depth since its release in 2000, but theres still a lot to learn. This completely revised sixth edition, organised around concepts and use cases, offers intermediate and advanced programmers a concise map of C# and.NET knowledge. By diving in, youll see why this Nutshell guide is recognised as the ultimate C# reference.', '60.00', 3, 250);

select * from books;

INSERT INTO customers (customerid, fname, lname, address, city, postal_code, country) VALUES
(null, 'milen', 'thomas', '228 albert street', 'waterloo', 'n2e2x7', 'Canada');

INSERT INTO publisher (publisherid, publisher_name) VALUES
(null, 'Wrox'),
(null, 'Wiley'),
(null, 'O''Reilly Media'),
(null, 'Apress'),
(null, 'Packt Publishing'),
(null, 'Addison-Wesley');

